version: '3'

services:
  # Run the wagtail app
  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.python
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app:delegated
    depends_on:
      - postgres
      - watch-static-files

  # Database
  postgres:
    image: postgres:11
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/:delegated

  # Rebuild static files automatically
  watch-static-files:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.node
    environment:
      # Need to specify the SHELL env var for chokidar
      - SHELL=/bin/sh
      # Force polling because inotify doesn't work on Docker Windows
      - CHOKIDAR_USEPOLLING=1
    command: npm run watch
    volumes:
      - .:/app:delegated
      - node_dependencies:/app/node_modules/:delegated

volumes:
  postgres_data:
  node_dependencies:
